CREATE DATABASE IF NOT EXISTS survivor;
USE survivor;

CREATE TABLE IF NOT EXISTS User
(
    id         INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email      VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    name       VARCHAR(255) NOT NULL,
    firstname  VARCHAR(255) NOT NULL,
    status     VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);