name: Build an Artefact Docker Compose and Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-pack:
    runs-on: ubuntu-latest

    permissions:
      contents: write #Set the write permission into gtihub file

    steps:
    - name: "Step 1: transfer the repo file to the new image"
      uses: actions/checkout@v4

    - name: "Step 2: setup DockerBuildX"
      uses: docker/setup-buildx-action@v3

    - name: "Step 3: build and rename the dockers image"
      run: |
        docker build -t survivor-backend:latest ./backend
        docker build -t survivor-frontend:latest ./front

    - name: "Step 4: builds docker image and save it"
      run: |
        mkdir -p docker-archives
        docker save -o docker-archives/backend.tar survivor-backend:latest
        docker save -o docker-archives/frontend.tar survivor-frontend:latest
        cp docker-compose.prod.yml docker-archives/docker-compose.yml

    - name: "Step 5: send the artefact to github"
      uses: actions/upload-artifact@v4
      with:
        name: survivor-docker-images
        path: docker-archives/
        retention-days: 7

    - name: "Step 6: Create GitHub Release and upload files"
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          docker-archives/backend.tar
          docker-archives/frontend.tar
          docker-archives/docker-compose.yml
        generate_release_notes: true